'------------------------------------------------------------------------------
'  <auto-generated>
'      This code was generated by coded UI test builder.
'      Version: 12.0.0.0
'
'      Changes to this file may cause incorrect behavior and will be lost if
'      the code is regenerated.
'  </auto-generated>
' ------------------------------------------------------------------------------

Imports System
Imports System.CodeDom.Compiler
Imports System.Collections.Generic
Imports System.Drawing
Imports System.Text.RegularExpressions
Imports System.Windows.Input
Imports Microsoft.VisualStudio.TestTools.UITest.Extension
Imports Microsoft.VisualStudio.TestTools.UITesting
Imports Microsoft.VisualStudio.TestTools.UITesting.WinControls
Imports Microsoft.VisualStudio.TestTools.UnitTesting
Imports Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard
Imports Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse
Imports MouseButtons = System.Windows.Forms.MouseButtons

Namespace SystemTestGUI
    
    <GeneratedCode("Coded UITest Builder", "12.0.31101.0")>  _
    Partial Public Class UIMap
        
        '''<summary>
        '''detils being added with 1/2 times, 1/2 dates and the #impt tag
        '''</summary>
        Public Sub add_details_time_date_impt()
            Dim uIUserInputEdit As WinEdit = Me.UIPlanner4LifeWindow.UIUserInputWindow.UIUserInputEdit

            'Type 'clear' in 'userInput' text box
            uIUserInputEdit.Text = Me.add_details_time_date_imptParams.UIUserInputEditText

            'Type '{Enter}' in 'userInput' text box
            Keyboard.SendKeys(uIUserInputEdit, Me.add_details_time_date_imptParams.UIUserInputEditSendKeys, ModifierKeys.None)

            'Type 'Y' in 'userInput' text box
            uIUserInputEdit.Text = Me.add_details_time_date_imptParams.UIUserInputEditText1

            'Type '{Enter}' in 'userInput' text box
            Keyboard.SendKeys(uIUserInputEdit, Me.add_details_time_date_imptParams.UIUserInputEditSendKeys1, ModifierKeys.None)

            'Type 'add event a' in 'userInput' text box
            uIUserInputEdit.Text = Me.add_details_time_date_imptParams.UIUserInputEditText2

            'Type '{Enter}' in 'userInput' text box
            Keyboard.SendKeys(uIUserInputEdit, Me.add_details_time_date_imptParams.UIUserInputEditSendKeys2, ModifierKeys.None)

            'Type 'add event b; date 150415' in 'userInput' text box
            uIUserInputEdit.Text = Me.add_details_time_date_imptParams.UIUserInputEditText3

            'Type '{Enter}' in 'userInput' text box
            Keyboard.SendKeys(uIUserInputEdit, Me.add_details_time_date_imptParams.UIUserInputEditSendKeys3, ModifierKeys.None)

            'Type 'add event c; date 150415 to 160415' in 'userInput' text box
            uIUserInputEdit.Text = Me.add_details_time_date_imptParams.UIUserInputEditText4

            'Type '{Enter}' in 'userInput' text box
            Keyboard.SendKeys(uIUserInputEdit, Me.add_details_time_date_imptParams.UIUserInputEditSendKeys4, ModifierKeys.None)

            'Type 'add event d; date 150415 to 160415; time 0800' in 'userInput' text box
            uIUserInputEdit.Text = Me.add_details_time_date_imptParams.UIUserInputEditText5

            'Type '{Enter}' in 'userInput' text box
            Keyboard.SendKeys(uIUserInputEdit, Me.add_details_time_date_imptParams.UIUserInputEditSendKeys5, ModifierKeys.None)

            'Type 'add event e; date 150415 to 160415; time 0800 to 0900' in 'userInput' text box
            uIUserInputEdit.Text = Me.add_details_time_date_imptParams.UIUserInputEditText6

            'Type '{Enter}' in 'userInput' text box
            Keyboard.SendKeys(uIUserInputEdit, Me.add_details_time_date_imptParams.UIUserInputEditSendKeys6, ModifierKeys.None)

            'Type 'add event f; date 160415 to 170415; time 0800 to 0900 #impt' in 'userInput' text box
            uIUserInputEdit.Text = Me.add_details_time_date_imptParams.UIUserInputEditText7

            'Type '{Enter}' in 'userInput' text box
            Keyboard.SendKeys(uIUserInputEdit, Me.add_details_time_date_imptParams.UIUserInputEditSendKeys7, ModifierKeys.None)

            'Type 'all' in 'userInput' text box
            uIUserInputEdit.Text = Me.add_details_time_date_imptParams.UIUserInputEditText8

            'Type '{Enter}' in 'userInput' text box
            Keyboard.SendKeys(uIUserInputEdit, Me.add_details_time_date_imptParams.UIUserInputEditSendKeys8, ModifierKeys.None)
        End Sub
        
        '''<summary>
        '''Assert for UIMap add_details_time_date_impt
        '''</summary>
        Public Sub assert_add_details_time_date_impt()
            Dim uIDisplayWindowEdit As WinEdit = Me.UIPlanner4LifeWindow.UIDisplayWindowWindow.UIDisplayWindowEdit

            'Verify that the 'Text' property of 'displayWindow' text box equals '1. event a 
            '2. event b Date: 15/4/15 
            '3. event c Date: 15/4/15 to 16/4/15 
            '4. event d Date: 15/4/15 to 16/4/15 Time: 0800 
            '5. event e Date: 15/4/15 to 16/4/15 Time: 0800 to 0900 
            '6. event f Date: 16/4/15 to 17/4/15 Time: 0800 to 0900 #impt
            ''
            Assert.AreEqual(Me.assert_add_details_time_date_imptExpectedValues.UIDisplayWindowEditText, uIDisplayWindowEdit.Text)
        End Sub
        
        '''<summary>
        '''inputs 3 events into home page and deletes the 2nd task
        '''</summary>
        Public Sub delete_test_in_home()
            Dim uIUserInputEdit As WinEdit = Me.UIPlanner4LifeWindow.UIUserInputWindow.UIUserInputEdit

            'Type 'clear' in 'userInput' text box
            uIUserInputEdit.Text = Me.delete_test_in_homeParams.UIUserInputEditText

            'Type '{Enter}' in 'userInput' text box
            Keyboard.SendKeys(uIUserInputEdit, Me.delete_test_in_homeParams.UIUserInputEditSendKeys, ModifierKeys.None)

            'Type 'Y' in 'userInput' text box
            uIUserInputEdit.Text = Me.delete_test_in_homeParams.UIUserInputEditText1

            'Type '{Enter}' in 'userInput' text box
            Keyboard.SendKeys(uIUserInputEdit, Me.delete_test_in_homeParams.UIUserInputEditSendKeys1, ModifierKeys.None)

            'Type 'add event a' in 'userInput' text box
            uIUserInputEdit.Text = Me.delete_test_in_homeParams.UIUserInputEditText2

            'Type '{Enter}' in 'userInput' text box
            Keyboard.SendKeys(uIUserInputEdit, Me.delete_test_in_homeParams.UIUserInputEditSendKeys2, ModifierKeys.None)

            'Type 'add event b' in 'userInput' text box
            uIUserInputEdit.Text = Me.delete_test_in_homeParams.UIUserInputEditText3

            'Type '{Enter}' in 'userInput' text box
            Keyboard.SendKeys(uIUserInputEdit, Me.delete_test_in_homeParams.UIUserInputEditSendKeys3, ModifierKeys.None)

            'Type 'add event c' in 'userInput' text box
            uIUserInputEdit.Text = Me.delete_test_in_homeParams.UIUserInputEditText4

            'Type '{Enter}' in 'userInput' text box
            Keyboard.SendKeys(uIUserInputEdit, Me.delete_test_in_homeParams.UIUserInputEditSendKeys4, ModifierKeys.None)

            'Type 'delete 2' in 'userInput' text box
            uIUserInputEdit.Text = Me.delete_test_in_homeParams.UIUserInputEditText5

            'Type '{Enter}' in 'userInput' text box
            Keyboard.SendKeys(uIUserInputEdit, Me.delete_test_in_homeParams.UIUserInputEditSendKeys5, ModifierKeys.None)

            'Type 'home' in 'userInput' text box
            uIUserInputEdit.Text = Me.delete_test_in_homeParams.UIUserInputEditText6

            'Type '{Enter}' in 'userInput' text box
            Keyboard.SendKeys(uIUserInputEdit, Me.delete_test_in_homeParams.UIUserInputEditSendKeys6, ModifierKeys.None)
        End Sub
        
        '''<summary>
        '''assert for UIMAP delete_test_in_home
        '''</summary>
        Public Sub assert_delete_test_in_home()
            Dim uIDisplayWindowEdit As WinEdit = Me.UIPlanner4LifeWindow.UIDisplayWindowWindow.UIDisplayWindowEdit

            'Verify that the 'Text' property of 'displayWindow' text box equals '1. event a 
            '2. event c 
            ''
            Assert.AreEqual(Me.assert_delete_test_in_homeExpectedValues.UIDisplayWindowEditText, uIDisplayWindowEdit.Text)
        End Sub
        
        #Region "Properties"
        Public Overridable ReadOnly Property add_details_time_date_imptParams() As add_details_time_date_imptParams
            Get
                If (Me.madd_details_time_date_imptParams Is Nothing) Then
                    Me.madd_details_time_date_imptParams = New add_details_time_date_imptParams()
                End If
                Return Me.madd_details_time_date_imptParams
            End Get
        End Property
        
        Public Overridable ReadOnly Property assert_add_details_time_date_imptExpectedValues() As assert_add_details_time_date_imptExpectedValues
            Get
                If (Me.massert_add_details_time_date_imptExpectedValues Is Nothing) Then
                    Me.massert_add_details_time_date_imptExpectedValues = New assert_add_details_time_date_imptExpectedValues()
                End If
                Return Me.massert_add_details_time_date_imptExpectedValues
            End Get
        End Property
        
        Public Overridable ReadOnly Property delete_test_in_homeParams() As delete_test_in_homeParams
            Get
                If (Me.mdelete_test_in_homeParams Is Nothing) Then
                    Me.mdelete_test_in_homeParams = New delete_test_in_homeParams()
                End If
                Return Me.mdelete_test_in_homeParams
            End Get
        End Property
        
        Public Overridable ReadOnly Property assert_delete_test_in_homeExpectedValues() As assert_delete_test_in_homeExpectedValues
            Get
                If (Me.massert_delete_test_in_homeExpectedValues Is Nothing) Then
                    Me.massert_delete_test_in_homeExpectedValues = New assert_delete_test_in_homeExpectedValues()
                End If
                Return Me.massert_delete_test_in_homeExpectedValues
            End Get
        End Property
        
        Public ReadOnly Property UIPlanner4LifeWindow() As UIPlanner4LifeWindow
            Get
                If (Me.mUIPlanner4LifeWindow Is Nothing) Then
                    Me.mUIPlanner4LifeWindow = New UIPlanner4LifeWindow()
                End If
                Return Me.mUIPlanner4LifeWindow
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private madd_details_time_date_imptParams As add_details_time_date_imptParams
        
        Private massert_add_details_time_date_imptExpectedValues As assert_add_details_time_date_imptExpectedValues
        
        Private mdelete_test_in_homeParams As delete_test_in_homeParams
        
        Private massert_delete_test_in_homeExpectedValues As assert_delete_test_in_homeExpectedValues
        
        Private mUIPlanner4LifeWindow As UIPlanner4LifeWindow
        #End Region
    End Class
    
    '''<summary>
    '''Parameters to be passed into 'add_details_time_date_impt'
    '''</summary>
    <GeneratedCode("Coded UITest Builder", "12.0.31101.0")>  _
    Public Class add_details_time_date_imptParams
        
        #Region "Fields"
        '''<summary>
        '''Type 'clear' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditText As String = "clear"
        
        '''<summary>
        '''Type '{Enter}' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditSendKeys As String = "{Enter}"
        
        '''<summary>
        '''Type 'Y' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditText1 As String = "Y"
        
        '''<summary>
        '''Type '{Enter}' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditSendKeys1 As String = "{Enter}"
        
        '''<summary>
        '''Type 'add event a' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditText2 As String = "add event a"
        
        '''<summary>
        '''Type '{Enter}' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditSendKeys2 As String = "{Enter}"
        
        '''<summary>
        '''Type 'add event b; date 150415' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditText3 As String = "add event b; date 150415"
        
        '''<summary>
        '''Type '{Enter}' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditSendKeys3 As String = "{Enter}"
        
        '''<summary>
        '''Type 'add event c; date 150415 to 160415' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditText4 As String = "add event c; date 150415 to 160415"
        
        '''<summary>
        '''Type '{Enter}' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditSendKeys4 As String = "{Enter}"
        
        '''<summary>
        '''Type 'add event d; date 150415 to 160415; time 0800' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditText5 As String = "add event d; date 150415 to 160415; time 0800"
        
        '''<summary>
        '''Type '{Enter}' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditSendKeys5 As String = "{Enter}"
        
        '''<summary>
        '''Type 'add event e; date 150415 to 160415; time 0800 to 0900' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditText6 As String = "add event e; date 150415 to 160415; time 0800 to 0900"
        
        '''<summary>
        '''Type '{Enter}' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditSendKeys6 As String = "{Enter}"
        
        '''<summary>
        '''Type 'add event f; date 160415 to 170415; time 0800 to 0900 #impt' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditText7 As String = "add event f; date 160415 to 170415; time 0800 to 0900 #impt"
        
        '''<summary>
        '''Type '{Enter}' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditSendKeys7 As String = "{Enter}"
        
        '''<summary>
        '''Type 'all' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditText8 As String = "all"
        
        '''<summary>
        '''Type '{Enter}' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditSendKeys8 As String = "{Enter}"
        #End Region
    End Class
    
    '''<summary>
    '''Parameters to be passed into 'assert_add_details_time_date_impt'
    '''</summary>
    <GeneratedCode("Coded UITest Builder", "12.0.31101.0")>  _
    Public Class assert_add_details_time_date_imptExpectedValues
        
        #Region "Fields"
        '''<summary>
        '''Verify that the 'Text' property of 'displayWindow' text box equals '1. event a 
        '''2. event b Date: 15/4/15 
        '''3. event c Date: 15/4/15 to 16/4/15 
        '''4. event d Date: 15/4/15 to 16/4/15 Time: 0800 
        '''5. event e Date: 15/4/15 to 16/4/15 Time: 0800 to 0900 
        '''6. event f Date: 16/4/15 to 17/4/15 Time: 0800 to 0900 #impt
        ''''
        '''</summary>
        Public UIDisplayWindowEditText As String = "1. event a "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"2. event b Date: 15/4/15 "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"3. event c Date: 15/4/15 to 16/4/15 "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"4. "& _ 
            "event d Date: 15/4/15 to 16/4/15 Time: 0800 "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"5. event e Date: 15/4/15 to 16/4/1"& _ 
            "5 Time: 0800 to 0900 "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"6. event f Date: 16/4/15 to 17/4/15 Time: 0800 to 0900 #i"& _ 
            "mpt"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)
        #End Region
    End Class
    
    '''<summary>
    '''Parameters to be passed into 'delete_test_in_home'
    '''</summary>
    <GeneratedCode("Coded UITest Builder", "12.0.31101.0")>  _
    Public Class delete_test_in_homeParams
        
        #Region "Fields"
        '''<summary>
        '''Type 'clear' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditText As String = "clear"
        
        '''<summary>
        '''Type '{Enter}' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditSendKeys As String = "{Enter}"
        
        '''<summary>
        '''Type 'Y' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditText1 As String = "Y"
        
        '''<summary>
        '''Type '{Enter}' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditSendKeys1 As String = "{Enter}"
        
        '''<summary>
        '''Type 'add event a' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditText2 As String = "add event a"
        
        '''<summary>
        '''Type '{Enter}' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditSendKeys2 As String = "{Enter}"
        
        '''<summary>
        '''Type 'add event b' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditText3 As String = "add event b"
        
        '''<summary>
        '''Type '{Enter}' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditSendKeys3 As String = "{Enter}"
        
        '''<summary>
        '''Type 'add event c' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditText4 As String = "add event c"
        
        '''<summary>
        '''Type '{Enter}' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditSendKeys4 As String = "{Enter}"
        
        '''<summary>
        '''Type 'delete 2' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditText5 As String = "delete 2"
        
        '''<summary>
        '''Type '{Enter}' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditSendKeys5 As String = "{Enter}"
        
        '''<summary>
        '''Type 'home' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditText6 As String = "home"
        
        '''<summary>
        '''Type '{Enter}' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditSendKeys6 As String = "{Enter}"
        #End Region
    End Class
    
    '''<summary>
    '''Parameters to be passed into 'assert_delete_test_in_home'
    '''</summary>
    <GeneratedCode("Coded UITest Builder", "12.0.31101.0")>  _
    Public Class assert_delete_test_in_homeExpectedValues
        
        #Region "Fields"
        '''<summary>
        '''Verify that the 'Text' property of 'displayWindow' text box equals '1. event a 
        '''2. event c 
        ''''
        '''</summary>
        Public UIDisplayWindowEditText As String = "1. event a "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"2. event c "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "12.0.31101.0")>  _
    Public Class UIPlanner4LifeWindow
        Inherits WinWindow
        
        Public Sub New()
            MyBase.New
            Me.SearchProperties(WinWindow.PropertyNames.Name) = "Planner4Life"
            Me.SearchProperties.Add(New PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains))
            Me.WindowTitles.Add("Planner4Life")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIUserInputWindow() As UIUserInputWindow
            Get
                If (Me.mUIUserInputWindow Is Nothing) Then
                    Me.mUIUserInputWindow = New UIUserInputWindow(Me)
                End If
                Return Me.mUIUserInputWindow
            End Get
        End Property
        
        Public ReadOnly Property UIDisplayWindowWindow() As UIDisplayWindowWindow
            Get
                If (Me.mUIDisplayWindowWindow Is Nothing) Then
                    Me.mUIDisplayWindowWindow = New UIDisplayWindowWindow(Me)
                End If
                Return Me.mUIDisplayWindowWindow
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIUserInputWindow As UIUserInputWindow
        
        Private mUIDisplayWindowWindow As UIDisplayWindowWindow
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "12.0.31101.0")>  _
    Public Class UIUserInputWindow
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.ControlName) = "userInput"
            Me.WindowTitles.Add("Planner4Life")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIUserInputEdit() As WinEdit
            Get
                If (Me.mUIUserInputEdit Is Nothing) Then
                    Me.mUIUserInputEdit = New WinEdit(Me)
                    Me.mUIUserInputEdit.WindowTitles.Add("Planner4Life")
                End If
                Return Me.mUIUserInputEdit
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIUserInputEdit As WinEdit
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "12.0.31101.0")>  _
    Public Class UIDisplayWindowWindow
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.ControlName) = "displayWindow"
            Me.WindowTitles.Add("Planner4Life")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIDisplayWindowEdit() As WinEdit
            Get
                If (Me.mUIDisplayWindowEdit Is Nothing) Then
                    Me.mUIDisplayWindowEdit = New WinEdit(Me)
                    Me.mUIDisplayWindowEdit.WindowTitles.Add("Planner4Life")
                End If
                Return Me.mUIDisplayWindowEdit
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIDisplayWindowEdit As WinEdit
        #End Region
    End Class
End Namespace
