'------------------------------------------------------------------------------
'  <auto-generated>
'      This code was generated by coded UI test builder.
'      Version: 12.0.0.0
'
'      Changes to this file may cause incorrect behavior and will be lost if
'      the code is regenerated.
'  </auto-generated>
' ------------------------------------------------------------------------------

Imports System
Imports System.CodeDom.Compiler
Imports System.Collections.Generic
Imports System.Drawing
Imports System.Text.RegularExpressions
Imports System.Windows.Input
Imports Microsoft.VisualStudio.TestTools.UITest.Extension
Imports Microsoft.VisualStudio.TestTools.UITesting
Imports Microsoft.VisualStudio.TestTools.UITesting.WinControls
Imports Microsoft.VisualStudio.TestTools.UnitTesting
Imports Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard
Imports Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse
Imports MouseButtons = System.Windows.Forms.MouseButtons

Namespace SystemTests
    
    <GeneratedCode("Coded UITest Builder", "12.0.31101.0")>  _
    Partial Public Class UIMap
        
        '''<summary>
        '''test for add with time and date, with time no date, with date no time, and no time no date
        '''</summary>
        Public Sub systemtest_add_time_date()
            Dim uIUserInputEdit As WinEdit = Me.UIItemWindow.UIUserInputWindow.UIUserInputEdit

            'Type 'add event a; date 030415 to 040415; time 0800 to 0900' in 'userInput' text box
            uIUserInputEdit.Text = Me.systemtest_add_time_dateParams.UIUserInputEditText

            'Type '{Enter}' in 'userInput' text box
            Keyboard.SendKeys(uIUserInputEdit, Me.systemtest_add_time_dateParams.UIUserInputEditSendKeys, ModifierKeys.None)

            'Type 'add event b; date 050415 to 060415' in 'userInput' text box
            uIUserInputEdit.Text = Me.systemtest_add_time_dateParams.UIUserInputEditText1

            'Type '{Enter}' in 'userInput' text box
            Keyboard.SendKeys(uIUserInputEdit, Me.systemtest_add_time_dateParams.UIUserInputEditSendKeys1, ModifierKeys.None)

            'Type 'add event c' in 'userInput' text box
            uIUserInputEdit.Text = Me.systemtest_add_time_dateParams.UIUserInputEditText2

            'Type '{Enter}' in 'userInput' text box
            Keyboard.SendKeys(uIUserInputEdit, Me.systemtest_add_time_dateParams.UIUserInputEditSendKeys2, ModifierKeys.None)

            'Type 'add event d; time 1000 to 1100' in 'userInput' text box
            uIUserInputEdit.Text = Me.systemtest_add_time_dateParams.UIUserInputEditText3

            'Type '{Enter}' in 'userInput' text box
            Keyboard.SendKeys(uIUserInputEdit, Me.systemtest_add_time_dateParams.UIUserInputEditSendKeys3, ModifierKeys.None)
        End Sub
        
        '''<summary>
        '''actions for add with time and date, no time have date, no date have time, and no date no time
        '''</summary>
        Public Sub userAdd_time_date()
            Dim uIUserInputEdit As WinEdit = Me.UIItemWindow.UIUserInputWindow.UIUserInputEdit

            'Type 'clear' in 'userInput' text box
            uIUserInputEdit.Text = Me.userAdd_time_dateParams.UIUserInputEditText

            'Type '{Enter}' in 'userInput' text box
            Keyboard.SendKeys(uIUserInputEdit, Me.userAdd_time_dateParams.UIUserInputEditSendKeys, ModifierKeys.None)

            'Type 'Y' in 'userInput' text box
            uIUserInputEdit.Text = Me.userAdd_time_dateParams.UIUserInputEditText1

            'Type '{Enter}' in 'userInput' text box
            Keyboard.SendKeys(uIUserInputEdit, Me.userAdd_time_dateParams.UIUserInputEditSendKeys1, ModifierKeys.None)

            'Type 'add event a; date 030415 to 040415' in 'userInput' text box
            uIUserInputEdit.Text = Me.userAdd_time_dateParams.UIUserInputEditText2

            'Type '{Enter}' in 'userInput' text box
            Keyboard.SendKeys(uIUserInputEdit, Me.userAdd_time_dateParams.UIUserInputEditSendKeys2, ModifierKeys.None)

            'Type 'add event b; time 1000 to 1100' in 'userInput' text box
            uIUserInputEdit.Text = Me.userAdd_time_dateParams.UIUserInputEditText3

            'Type '{Enter}' in 'userInput' text box
            Keyboard.SendKeys(uIUserInputEdit, Me.userAdd_time_dateParams.UIUserInputEditSendKeys3, ModifierKeys.None)

            'Type 'add event c; date 040515 to 060415; time 1000 to 1100' in 'userInput' text box
            uIUserInputEdit.Text = Me.userAdd_time_dateParams.UIUserInputEditText4

            'Type '{Enter}' in 'userInput' text box
            Keyboard.SendKeys(uIUserInputEdit, Me.userAdd_time_dateParams.UIUserInputEditSendKeys4, ModifierKeys.None)

            'Type 'add event d' in 'userInput' text box
            uIUserInputEdit.Text = Me.userAdd_time_dateParams.UIUserInputEditText5

            'Type '{Enter}' in 'userInput' text box
            Keyboard.SendKeys(uIUserInputEdit, Me.userAdd_time_dateParams.UIUserInputEditSendKeys5, ModifierKeys.None)
        End Sub
        
        '''<summary>
        '''assert_userAdd_time_date - Use 'assert_userAdd_time_dateExpectedValues' to pass parameters into this method.
        '''</summary>
        Public Sub assert_userAdd_time_date()
            Dim uIDisplayWindowEdit As WinEdit = Me.UIItemWindow.UIDisplayWindowWindow.UIDisplayWindowEdit

            'Verify that the 'Text' property of 'displayWindow' text box equals '1. event d 
            '2. event a 3/4/15 to 4/4/15
            '3. event b 1000 to 1100
            '4. event c 4/5/15 to 6/4/151000 to 1100
            ''
            Assert.AreEqual(Me.assert_userAdd_time_dateExpectedValues.UIDisplayWindowEditText, uIDisplayWindowEdit.Text, "assert userAdd_time_date failed!")
        End Sub
        
        #Region "Properties"
        Public Overridable ReadOnly Property systemtest_add_time_dateParams() As systemtest_add_time_dateParams
            Get
                If (Me.msystemtest_add_time_dateParams Is Nothing) Then
                    Me.msystemtest_add_time_dateParams = New systemtest_add_time_dateParams()
                End If
                Return Me.msystemtest_add_time_dateParams
            End Get
        End Property
        
        Public Overridable ReadOnly Property userAdd_time_dateParams() As userAdd_time_dateParams
            Get
                If (Me.muserAdd_time_dateParams Is Nothing) Then
                    Me.muserAdd_time_dateParams = New userAdd_time_dateParams()
                End If
                Return Me.muserAdd_time_dateParams
            End Get
        End Property
        
        Public Overridable ReadOnly Property assert_userAdd_time_dateExpectedValues() As assert_userAdd_time_dateExpectedValues
            Get
                If (Me.massert_userAdd_time_dateExpectedValues Is Nothing) Then
                    Me.massert_userAdd_time_dateExpectedValues = New assert_userAdd_time_dateExpectedValues()
                End If
                Return Me.massert_userAdd_time_dateExpectedValues
            End Get
        End Property
        
        Public ReadOnly Property UIItemWindow() As UIItemWindow
            Get
                If (Me.mUIItemWindow Is Nothing) Then
                    Me.mUIItemWindow = New UIItemWindow()
                End If
                Return Me.mUIItemWindow
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private msystemtest_add_time_dateParams As systemtest_add_time_dateParams
        
        Private muserAdd_time_dateParams As userAdd_time_dateParams
        
        Private massert_userAdd_time_dateExpectedValues As assert_userAdd_time_dateExpectedValues
        
        Private mUIItemWindow As UIItemWindow
        #End Region
    End Class
    
    '''<summary>
    '''Parameters to be passed into 'systemtest_add_time_date'
    '''</summary>
    <GeneratedCode("Coded UITest Builder", "12.0.31101.0")>  _
    Public Class systemtest_add_time_dateParams
        
        #Region "Fields"
        '''<summary>
        '''Type 'add event a; date 030415 to 040415; time 0800 to 0900' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditText As String = "add event a; date 030415 to 040415; time 0800 to 0900"
        
        '''<summary>
        '''Type '{Enter}' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditSendKeys As String = "{Enter}"
        
        '''<summary>
        '''Type 'add event b; date 050415 to 060415' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditText1 As String = "add event b; date 050415 to 060415"
        
        '''<summary>
        '''Type '{Enter}' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditSendKeys1 As String = "{Enter}"
        
        '''<summary>
        '''Type 'add event c' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditText2 As String = "add event c"
        
        '''<summary>
        '''Type '{Enter}' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditSendKeys2 As String = "{Enter}"
        
        '''<summary>
        '''Type 'add event d; time 1000 to 1100' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditText3 As String = "add event d; time 1000 to 1100"
        
        '''<summary>
        '''Type '{Enter}' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditSendKeys3 As String = "{Enter}"
        #End Region
    End Class
    
    '''<summary>
    '''Parameters to be passed into 'userAdd_time_date'
    '''</summary>
    <GeneratedCode("Coded UITest Builder", "12.0.31101.0")>  _
    Public Class userAdd_time_dateParams
        
        #Region "Fields"
        '''<summary>
        '''Type 'clear' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditText As String = "clear"
        
        '''<summary>
        '''Type '{Enter}' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditSendKeys As String = "{Enter}"
        
        '''<summary>
        '''Type 'Y' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditText1 As String = "Y"
        
        '''<summary>
        '''Type '{Enter}' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditSendKeys1 As String = "{Enter}"
        
        '''<summary>
        '''Type 'add event a; date 030415 to 040415' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditText2 As String = "add event a; date 030415 to 040415"
        
        '''<summary>
        '''Type '{Enter}' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditSendKeys2 As String = "{Enter}"
        
        '''<summary>
        '''Type 'add event b; time 1000 to 1100' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditText3 As String = "add event b; time 1000 to 1100"
        
        '''<summary>
        '''Type '{Enter}' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditSendKeys3 As String = "{Enter}"
        
        '''<summary>
        '''Type 'add event c; date 040515 to 060415; time 1000 to 1100' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditText4 As String = "add event c; date 040515 to 060415; time 1000 to 1100"
        
        '''<summary>
        '''Type '{Enter}' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditSendKeys4 As String = "{Enter}"
        
        '''<summary>
        '''Type 'add event d' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditText5 As String = "add event d"
        
        '''<summary>
        '''Type '{Enter}' in 'userInput' text box
        '''</summary>
        Public UIUserInputEditSendKeys5 As String = "{Enter}"
        #End Region
    End Class
    
    '''<summary>
    '''Parameters to be passed into 'assert_userAdd_time_date'
    '''</summary>
    <GeneratedCode("Coded UITest Builder", "12.0.31101.0")>  _
    Public Class assert_userAdd_time_dateExpectedValues
        
        #Region "Fields"
        '''<summary>
        '''Verify that the 'Text' property of 'displayWindow' text box equals '1. event d 
        '''2. event a 3/4/15 to 4/4/15
        '''3. event b 1000 to 1100
        '''4. event c 4/5/15 to 6/4/151000 to 1100
        ''''
        '''</summary>
        Public UIDisplayWindowEditText As String = "1. event d "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"2. event a 3/4/15 to 4/4/15"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"3. event b 1000 to 1100"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"4. event c 4/5"& _ 
            "/15 to 6/4/151000 to 1100"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "12.0.31101.0")>  _
    Public Class UIItemWindow
        Inherits WinWindow
        
        Public Sub New()
            MyBase.New
            Me.SearchProperties(WinWindow.PropertyNames.AccessibleName) = "Desktop"
            Me.SearchProperties(WinWindow.PropertyNames.ClassName) = "#32769"
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIUserInputWindow() As UIUserInputWindow
            Get
                If (Me.mUIUserInputWindow Is Nothing) Then
                    Me.mUIUserInputWindow = New UIUserInputWindow(Me)
                End If
                Return Me.mUIUserInputWindow
            End Get
        End Property
        
        Public ReadOnly Property UIDisplayWindowWindow() As UIDisplayWindowWindow
            Get
                If (Me.mUIDisplayWindowWindow Is Nothing) Then
                    Me.mUIDisplayWindowWindow = New UIDisplayWindowWindow(Me)
                End If
                Return Me.mUIDisplayWindowWindow
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIUserInputWindow As UIUserInputWindow
        
        Private mUIDisplayWindowWindow As UIDisplayWindowWindow
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "12.0.31101.0")>  _
    Public Class UIUserInputWindow
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.ControlName) = "userInput"
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIUserInputEdit() As WinEdit
            Get
                If (Me.mUIUserInputEdit Is Nothing) Then
                    Me.mUIUserInputEdit = New WinEdit(Me)
                End If
                Return Me.mUIUserInputEdit
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIUserInputEdit As WinEdit
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "12.0.31101.0")>  _
    Public Class UIDisplayWindowWindow
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.ControlName) = "displayWindow"
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIDisplayWindowEdit() As WinEdit
            Get
                If (Me.mUIDisplayWindowEdit Is Nothing) Then
                    Me.mUIDisplayWindowEdit = New WinEdit(Me)
                End If
                Return Me.mUIDisplayWindowEdit
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIDisplayWindowEdit As WinEdit
        #End Region
    End Class
End Namespace
